// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Change to return Android options
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHuELnvdTLeZ1n-MF8QwlCDwQ1ljnlfc',
    appId: '1:25967406325:web:13cd5562f3d225ba84e9bc',
    messagingSenderId: '25967406325',
    projectId: 'authentication-4a899',
    authDomain: 'authentication-4a899.firebaseapp.com',
    storageBucket: 'authentication-4a899.appspot.com',
    measurementId: 'G-WMV9PFLWR8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlpbfzmMDJOwv4BQZg4umJXNJOTiWaXUM',
    appId: '1:25967406325:ios:641f94eaa1bf688d84e9bc',
    messagingSenderId: '25967406325',
    projectId: 'authentication-4a899',
    storageBucket: 'authentication-4a899.appspot.com',
    iosBundleId: 'com.example.mediMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlpbfzmMDJOwv4BQZg4umJXNJOTiWaXUM',
    appId: '1:25967406325:ios:641f94eaa1bf688d84e9bc',
    messagingSenderId: '25967406325',
    projectId: 'authentication-4a899',
    storageBucket: 'authentication-4a899.appspot.com',
    iosBundleId: 'com.example.mediMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqHuELnvdTLeZ1n-MF8QwlCDwQ1ljnlfc',
    appId: '1:25967406325:web:cbefeee5304c694684e9bc',
    messagingSenderId: '25967406325',
    projectId: 'authentication-4a899',
    authDomain: 'authentication-4a899.firebaseapp.com',
    storageBucket: 'authentication-4a899.appspot.com',
    measurementId: 'G-D9ZZC91TKF',
  );

  static const FirebaseOptions android = FirebaseOptions( // Add Android options here
    apiKey: 'YOUR_ANDROID_API_KEY', // Replace with your actual API Key
    appId: '1:YOUR_APP_ID:android:YOUR_ANDROID_APP_ID', // Replace with your actual App ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Replace with your actual Messaging Sender ID
    projectId: 'authentication-4a899',
    storageBucket: 'authentication-4a899.appspot.com',
  );
}